### PR TITLE
Add reset function.

### PR DESCRIPTION
**Pull request by reitermarkus**
Add function for resetting the sensor, either soft or hard.

### CODE REVIEW

**Comment by miek** [comment]
I don't think that the General Call reset implementation is correct. The datasheet says that it should be a write to I2C address 0, but this is treating it as a normal command written to the SHT3x's address.

**Comment by reitermarkus** [comment]
You're right, @miek, I guess the “General Call” reset should probably not be part of this crate then since it applies to any device.

**Comment by reitermarkus** [comment]
@miek, I removed the general reset.

**Comment by reitermarkus** [comment]
@miek, could you have another look at this? Thanks.

**Comment by miek** [comment]
Merged, thanks! Sorry for the delay.

**Comment by reitermarkus** [comment]
No worries, @miek. 

Would be great if you could also release a new version with these changes.

**Pull request merged**
